version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"

  # JavaScript / Node.js dependencies
  - package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"

  # Python dependencies via requirements.txt
  - package-ecosystem: "pip"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
